# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a87d54259473deb3e8c93506f5e26c7caa9697cef9cace641376f5f73ab09eb072fadcb0d49f081858549203483074b469db3711f51fd313d5ad2beb30c7f06

test:
  secret_key_base: 04f210edf52bb1de89b537e614f0115c3b8bb127485fba7ca2591e8eddb3af8a5a694401725ddf6d3717afc07d2392a5b8f4d3506f276e160f80e321d54034f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
